---

env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    # - ignorePackages
    - js: always
  no-console: 0
  no-underscore-dangle: [2, {"allow": ["__filename", "__dirname"]}]
